---
- name: This play ist to download the latest war file from nexus
  hosts: localhost
  become: true
  vars_files:
    - /opt/playbooks/variables.yaml

  tasks:
     - name: download the war file
       shell: 'curl -u admin:admin -L "http://10.234.34.152:8081/service/rest/v1/search/assets/download?sort=version&repository=VinaysDevOpsLab-RELEASE&maven.groupId=com.vinaysdevopslab&maven.artifactId=VinayDevOpsLab&maven.extension=war" -H "accept: application/json" --output /home/ansibleadmin/latest.war'
       args:
          chdir: "{{ changedir_location }}"


- name: Deploy the latest war file to apache tomcat
  hosts: tomcat
  become: true
  vars_files:
    - /opt/playbooks/variables.yaml
  tasks:
      - copy:
          src: "{{ item }}"
          dest: "{{ destination_location }}"
          owner: tomcat
          group: tomcat
          mode: u+rwx,g+rwx,o-rwx
        with_fileglob:
          - "{{ buildartifact_location }}"
...
