---
- name: This play ist to download the latest war file from nexus
  hosts: localhost
  become: true

  tasks:
     - name: download the war file
       shell: 'curl -u admin:admin -L "http://10.234.34.152:8081/service/rest/v1/search/assets/download?sort=version&repository=VinaysDevOpsLab-RELEASE&maven.groupId=com.vinaysdevopslab&maven.artifactId=VinayDevOpsLab&maven.extension=war" -H "accept: application/json" --output /home/ansibleadmin/latest.war'
       args:
          chdir: /home/ansibleadmin


- name: Deploy the latest war file to apache tomcat
  hosts: tomcat
  become: true
  tasks:
      - copy:
          src: "{{ item }}"
          dest: "/opt/apache-tomcat-9.0.52/webapps/"
        with_fileglob:
          - "/home/ansibleadmin/*.war"
...
